### ISSUE TITLE
Roadmap 2023

### ISSUE THREAD

**Issue by kushalkolar** [kushalkolar/fastplotlib#55]
- [ ] API
  - [ ] module reorganization, #53
  - [ ] add suffix `Graphic` to all Graphics classes
  - [ ] Use matplotlib-like names for aspects of the API? Like `vmin` `vmax` for familiarity?
- [ ] Graphics
  - [ ] Polygons
    - [ ] Rectangle
    - [ ] Ellipses
    - [ ] Polygons
    - [ ] Allow drawing and reshaping with mouse events
  - [ ] Polyhedron
  - [ ] Ellipsoid
  - [ ] Volume #50 
- [ ] Graphic Collections
  - [ ] LineCollection
  - [ ] LineStack (useful for neural data)
  - [ ] PolygonCollection
- [ ] Interactivity Interface
  - [ ] High level interactivity interface to define events between Graphics #39 
  - [ ] “graphic-like” classes for sub-selecting data which have methods that get the data of any graphics underneath the selection.
    - [ ] LinearRegionSelector - similar to pyqtgraph LinearRegionItem
    - [ ] RectangleRegionSelection
    - [ ] PolygonRegionSelection
    - [ ] VolumeRegionSelection?
- [ ] Text - need to wait for pygfx to merge Text renderer https://github.com/pygfx/pygfx/pull/305 
- [ ] Subplot/View area stuff
  - [ ] refactor `Subplot`, create a new class `ViewArea` which is used by both `Subplot` and `DockedViewport` #30 
  - [ ] Axes with ticks and labels (see text)
  - [ ] Autoscale to fill the “view” w.r.t. data bounds, analogous to pyqtgraph “A” button thing, current ideas: https://github.com/pygfx/pygfx/issues/388 
- [ ] "Docked" viewports - in progress #30 
  - [ ] Histogram to adjust vmin vmax for image data
  - [ ] Legends
  - [ ] Colorbars
- [ ] Widgets - in progress
  - [ ] ImageWidget #51 
  - Do we need more types of widgets? Line plots? Scatter plots? The `ImageWidget` is due to the complex n-dimensional nature of imaging data.
- [ ] docs, #49
